//
// Copyright (c) Brian Hernandez. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
//

using System;
using UnityEngine;
using MFlight;

/// <summary>
/// This is a very demo-ey example of how to interpret the input generated by the
/// MouseFlightController. The plane flies towards the MouseAimPos automatically in
/// a similar fashion to how War Thunder's Instructor does it. There are also
/// keyboard overrides for flight control. It's not perfect, but it works well enough
/// for an example.
/// </summary>
[RequireComponent(typeof(Rigidbody))]
public class SubmarineController : MonoBehaviour
{
    [Header("Components")]
    [SerializeField] private MouseFlightController controller = null;

    [Header("Physics")]
    [Tooltip("Force to push submarine forwards with")] public float thrust = 100f;
    [Tooltip("Force to push Submarine vertically with")] public float verticalThrust = 100f;
    [Tooltip("Force to push Submarine horizontally with")] public float horizontalThrust = 100f;
    [Tooltip("need for speed maximum thust")] public float maxthrust = 69f;
    [Tooltip("Pitch, Yaw, Roll")] public Vector3 turnTorque = new Vector3(90f, 25f, 45f);
    [Tooltip("Multiplier for all forces")] public float forceMult = 1000f;

    [Header("Autopilot")]
    [Tooltip("Sensitivity for autopilot flight.")] public float sensitivity = 5f;
    [Tooltip("Angle at which airplane banks fully into target.")] public float aggressiveTurnAngle = 10f;

    [Header("Input")]
    [SerializeField] [Range(-1f, 1f)] private float pitch = 0f;
    [SerializeField] [Range(-1f, 1f)] private float yaw = 0f;
    [SerializeField] [Range(-1f, 1f)] private float roll = 0f;

    public float Pitch { set { pitch = Mathf.Clamp(value, -1f, 1f); } get { return pitch; } }
    public float Yaw { set { yaw = Mathf.Clamp(value, -1f, 1f); } get { return yaw; } }
    public float Roll { set { roll = Mathf.Clamp(value, -1f, 1f); } get { return roll; } }

    private Rigidbody rb;

    private bool rollOverride = false;
    private bool pitchOverride = false;

    private void Awake()
    {
        rb = GetComponent<Rigidbody>();

        if (controller == null)
            Debug.LogError(name + ": Plane - Missing reference to MouseFlightController!");
    }

    private void Start()
    {
        //Lock Cursor
        Cursor.lockState = CursorLockMode.Confined;
        Cursor.visible = false;
    }

    private float verticalMovement;
    private float horizontalMovement;

    public Vector2 GetSubmarineInput => new Vector2(verticalMovement, horizontalMovement);

    private void Update()
    {
        verticalMovement = Input.GetAxis("Vertical");

        if (Input.GetKeyDown(KeyCode.Space)) ToggleThrust();
        if (engineToggle) ChangeSpeed(0);
        else if (Input.GetKey(KeyCode.LeftShift)) ChangeSpeed(maxthrust);
        else ChangeSpeed(thrust);
        // When the player commands their own stick input, it should override what the
        // autopilot is trying to do.
        rollOverride = false;
        pitchOverride = false;

        Vector3 v3Angle = transform.rotation.eulerAngles;

        horizontalMovement = Input.GetAxis("Horizontal");

        // Calculate the autopilot stick inputs.
        float autoYaw = 0f;
        float autoPitch = 0f;
        float autoRoll = 0f;
        if (controller != null)
            RunAutopilot(controller.MouseAimPos, out autoYaw, out autoPitch, out autoRoll);

        // Use either keyboard or autopilot input.
        yaw = autoYaw;
        pitch = autoPitch;
        roll = (rollOverride) ? horizontalMovement : autoRoll;
    }

    private bool engineToggle = true;

    private void ToggleThrust()
    {
        engineToggle = !engineToggle;
    }

    private float previousSpeed, speedI = 0f;
    private float currentThrust;

    public float GetCurrentThrust => currentThrust;



    void ChangeSpeed(float speed)
    {
        //if our previous speed is not our current input speed, reset speedI to 0
        if (previousSpeed != speed)
        {
            previousSpeed = speed;
            speedI = 0f;
        }

        //calculate our current speed by lerping between the new speed and current speed
        currentThrust = Mathf.Lerp(currentThrust, speed, (speedI + Time.deltaTime) * 5);
    }

    private void RunAutopilot(Vector3 flyTarget, out float yaw, out float pitch, out float roll)
    {
        // This is my usual trick of converting the fly to position to local space.
        // You can derive a lot of information from where the target is relative to self.
        var localFlyTarget = transform.InverseTransformPoint(flyTarget).normalized * sensitivity;
        var angleOffTarget = Vector3.Angle(transform.forward, flyTarget - transform.position);

        // IMPORTANT!
        // These inputs are created proportionally. This means it can be prone to
        // overshooting. The physics in this example are tweaked so that it's not a big
        // issue, but in something with different or more realistic physics this might
        // not be the case. Use of a PID controller for each axis is highly recommended.

        // ====================
        // PITCH AND YAW
        // ====================

        // Yaw/Pitch into the target so as to put it directly in front of the aircraft.
        // A target is directly in front the aircraft if the relative X and Y are both
        // zero. Note this does not handle for the case where the target is directly behind.
        yaw = Mathf.Clamp(localFlyTarget.x, -1f, 1f);
        pitch = -Mathf.Clamp(localFlyTarget.y, -1f, 1f);

        // ====================
        // ROLL
        // ====================

        // Roll is a little special because there are two different roll commands depending
        // on the situation. When the target is off axis, then the plane should roll into it.
        // When the target is directly in front, the plane should fly wings level.

        // An "aggressive roll" is input such that the aircraft rolls into the target so
        // that pitching up (handled above) will put the nose onto the target. This is
        // done by rolling such that the X component of the target's position is zeroed.
        var agressiveRoll = Mathf.Clamp(localFlyTarget.x, -1f, 1f);

        // A "wings level roll" is a roll commands the aircraft to fly wings level.
        // This can be done by zeroing out the Y component of the aircraft's right.
        var wingsLevelRoll = transform.right.y;

        // Blend between auto level and banking into the target.
        var wingsLevelInfluence = Mathf.InverseLerp(0f, aggressiveTurnAngle, angleOffTarget);
        roll = Mathf.Lerp(wingsLevelRoll, agressiveRoll, wingsLevelInfluence);
    }
    public Vector3 moveDirection;
    private void FixedUpdate()
    {

        moveDirection = (Vector3.up * verticalThrust * verticalMovement * forceMult * 100) + (Vector3.right * horizontalThrust * horizontalMovement * forceMult * 100);
        // Ultra simple flight where the plane just gets pushed forward and manipulated
        // with torques to turn.
        rb.AddRelativeForce(((Vector3.forward * currentThrust * forceMult * 100) + moveDirection) * Time.fixedDeltaTime, ForceMode.Force);
        rb.AddRelativeTorque(new Vector3(turnTorque.x * pitch,
                                            turnTorque.y * yaw,
                                            -turnTorque.z * roll) * forceMult,
                                ForceMode.Force);


    }
}


   